---
#- name: Base configuration (as root) which sets up deploy user and changes SSH port and SSH user access to lock down
#  hosts: all
#  vars:
#    ansible_user: "{{ linux.root_user }}"
#    ansible_ssh_pass: "{{ linux.root_password }}"
#  roles:
#    - base
#  gather_facts: False

- name: Install all other roles as 'deploy'
  hosts: all
  vars:
    ansible_user: "{{ linux.deploy_user }}"
    ansible_ssh_pass: "{{ linux.deploy_password }}"
    ansible_sudo_pass: "{{ linux.deploy_password }}"
    ansible_port: "{{ linux.ssh_port }}"
  become: yes
  roles:
    #- base  # Configure base CentOS 7 with deploy user, set up firewall, run non-std SSH port
    #- yum-cron  # Keep the system up-to-date
    #- emacs  # Gotta have my favorite editor on the system
    #- ntp  # Keep clock in sync
    #- php7_0  # P in lamP
    #- httpd  # A in lAmp
    #- mysql5_7  # M in laMp
    #- check_scripts  # To check on httpd, mysqld, and track memory usage
    #- activate_prefork  # To use standard MPM prefork mode with mod_php on Apache (the LAMP default)
    #- activate_event  # Optimized for serving files...needs FCGI and php-fpm
    #- wordpress  # Install WordPress and its CLI
    #- wordpress_ownerperm  # Update file ownership and permissions in WordPress directory
    #- wp_ht  # Update .htaccess to lock down wp-admin/ to only certain IP addresses
