---
- name: Check if WordPress already installed
  stat:
    path: /var/www/html/wp-blog-header.php
  register: wordpress_file

# The WordPress configuration tasks in the block below will only execute if WordPress was downloaded above

### BEGIN BLOCK #######################################################################################################

- block:

  - name: Ensure /var/www/html directory is empty
    shell: rm -rf /var/www/html/*

  - name: Download and expand WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html
      remote_src: True

  - name: Move WordPress files up a level so they're directly under /var/www/html/
    shell: "mv wordpress/* ."
    args:
      chdir: /var/www/html/
      removes: /var/www/html/wordpress/index.php
      creates: /var/www/html/index.php

  - name: Remove empty /var/www/html/wordpress directory...artifact from WordPress download and unzip
    file:
      path: /var/www/html/wordpress
      state: absent

  - name: Fetch random salts for WordPress config
    local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
    register: wp_salt

  - name: Update WordPress config file from template
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wp-config.php

  - name: Change owner/group of Wordpress files
    file:
      path: "{{ wordpress.root_directory }}/"
      state: directory
      recurse: yes
      owner: "{{ linux.deploy_user }}"
      group: apache

  - name: Ensure all Wordpress directories are 0755
    command: find {{ wordpress.root_directory }} -type d -exec chmod -c 0755 {} \;
    register: chmod_result
    changed_when: "chmod_result.stdout != \"\""

  - name: Ensure all Wordpress files are 0644
    command: find {{ wordpress.root_directory }} -type f -exec chmod -c 0644 {} \;
    register: chmod_result
    changed_when: "chmod_result.stdout != \"\""

  - name: Special permissions for wp-config.php
    file:
      path: "{{ wordpress.root_directory }}/wp-config.php"
      state: file
      mode: 0660

  - name: Drop wordpress database
    mysql_db:
      name: "{{ db.wp_name }}"
      state: absent
      login_password: "{{ db.root_password }}"

  - name: (Re)Create WordPress database
    mysql_db:
      name: "{{ db.wp_name }}"
      state: present
      login_password: "{{ db.root_password }}"

  - name: Create WordPress database user
    mysql_user:
      name: "{{ db.wp_user }}"
      password: "{{ db.wp_password }}"
      priv: '{{ db.wp_name }}.*:ALL'
      host: 'localhost'
      state: present
      login_password: "{{ db.root_password }}"

  - name: Check if wp-cli installed
    stat:
      path: /usr/local/bin/wp
    register: wp_cli

  - name: Retrieve wp-cli
    get_url:
      url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      dest: /usr/local/bin
    when: not wp_cli.stat.exists

  - name: Rename wp-cli
    command: mv /usr/local/bin/wp-cli.phar /usr/local/bin/wp
    when: not wp_cli.stat.exists

  - name: Change wp(-cli) to executable
    file:
      path: /usr/local/bin/wp
      owner: root
      group: root
      mode: 0755

  - name: Update httpd.conf from template
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart httpd

  - name: Add current machine to wp-admin access
    linetofile:
      path: /var/www/html/.htaccess
      insertafter: 'Files.*wp-admin.php[^O]*Order deny,allow'
      line: '1.2.3.4 # Andy Fraley home'

  when:
    not wordpress_file.stat.exists

### END BLOCK #########################################################################################################
