---
- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes
  become: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
  become: yes
