---
- name: Ensure /root/bin present
  file:
    path: /root/bin
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy 'check' script
  template:
    src: check_httpd_and_mysqld
    dest: /root/bin
    owner: root
    group: root
    mode: 755

- name: Copy 'restart' script
  template:
    src: restart_httpd_and_mysqld
    dest: /root/bin
    owner: root
    group: root
    mode: 755

- name: Copy 'track memory' script
  template:
    src: track_free_memory
    dest: /root/bin
    owner: root
    group: root
    mode: 755

- name: Copy 'upgrade wordpress' script
  template:
    src: upgrade_wp.j2
    dest: /root/bin/upgrade_wp
    owner: root
    group: root
    mode: 755

- name: Copy 'update plugins' script
  template:
    src: update_plugins.j2
    dest: /root/bin/update_plugins
    owner: root
    group: root
    mode: 755

- name: Copy check_script logrotate config file
  template:
    src: check_scripts
    dest: /etc/logrotate.d
    owner: root
    group: root
    mode: 644

- name: "Cron 'check' script"
  cron:
    name: Check if httpd and mysqld are running
    minute: "*/5"
    job: "/root/bin/check_httpd_and_mysqld > /dev/null 2>&1"
  notify:
  - restart crond

- name: "Cron 'track free' script"
  cron:
    name: Track free memory
    minute: "*/5"
    job: "/root/bin/track_free_memory > /dev/null 2>&1"
  notify:
  - restart crond

- name: "Cron 'restart' script"
  cron:
    name: Restart httpd and mysqld (reclaim memory)
    hour: "5"
    minute: "1"
    job: "/root/bin/track_free_memory > /dev/null 2>&1"
  notify:
  - restart crond

- name: "Cron WordPress core upgrade"
  cron:
    name: Upgrade WordPress core if update is available
    hour: "6"
    minute: "1"
    job: "/root/bin/upgrade_wp >/dev/null 2>&1"
  notify:
  - restart crond

- name: "Cron WordPress plugins upgrade"
  cron:
    name: Upgrade WordPress plugins if updates are available for any
    hour: "6"
    minute: "31"
    job: "/root/bin/update_plugins >/dev/null 2>&1"
  notify:
  - restart crond
