linux:
  root_user: "{{ vault_linux.root_user }}"
  root_password: "{{ vault_linux.root_password }}"

db:
  root_password: "{{ vault_db.root_password }}"
  wp_name: "{{ vault_db.wp_name }}"
  wp_user: "{{ vault_db.wp_user }}"
  wp_password: "{{ vault_db.wp_password }}"
