---
- name: Install emacs
  yum: name={{ item }} state=present
  with_items:
  - emacs

- name: Set up emacs as default editor for deploy user
  lineinfile:
    dest: '/home/{{ linux.deploy_user }}/.bash_profile'
    regexp: 'export EDITOR'
    line: "export EDITOR=emacs"
    state: present

- name: Set up emacs as default editor for root user
  lineinfile:
    dest: '/root/.bash_profile'
    regexp: 'export EDITOR'
    line: "export EDITOR=emacs"
    state: present

- name: Set up "clean" alias/script for deploy user
  lineinfile:
    dest: "/home/{{ linux.deploy_user }}/.bashrc"
    regexp: 'alias clean'
    line: "alias clean='rm -f *~;rm -f \\#*\\#;rm -f \\.*~'"
    state: present

- name: Set up "clean" alias/script for root user
  lineinfile:
    dest: '/root/.bashrc'
    regexp: 'alias clean'
    line: "alias clean='rm -f *~;rm -f \\#*\\#;rm -f \\.*~'"
    state: present
