---
- name: Does {{ fullpath_filename }} exist?
  stat:
    path: "{{ fullpath_filename }}"
  register: checked_file

- name: Create {{ fullpath_filename }} as empty webserver-writeable file if it doesn't exist
  file:
    path: "{{ fullpath_filename }}"
    state: touch
    owner: "{{ webserver.user }}"
    group: "{{ webserver.group }}"
    mode: 0644
    setype: httpd_sys_rw_content_t
  when: not checked_file.stat.exists is defined or not checked_file.stat.exists

- name: Ensure {{ fullpath_filename }} is webserver-writeable if it does exist
  file:
    path: "{{ fullpath_filename }}"
    state: file
    owner: "{{ webserver.user }}"
    group: "{{ webserver.group }}"
    mode: 0644
    setype: httpd_sys_rw_content_t
  when: checked_file.stat.exists is defined and checked_file.stat.exists
