---
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes

- name: Add Webtatic PHP repository
  yum_repository:
    name: webtatic
    description: Webtatic YUM repo
    mirrorlist: https://mirror.webtatic.com/yum/el7/x86_64/mirrorlist
    gpgkey: https://mirror.webtatic.com/yum/RPM-GPG-KEY-webtatic-el7
    gpgcheck: yes

- name: Install PHP 7.0
  yum: name={{ item }} state=latest
  with_items:
  - php70w
  - php70w-cli
  - php70w-mysql
  - php70w-fpm
  notify: restart php-fpm
