---
- name: Enable mod_php7
  apache2_module:
    state: present
    name: php7.0
  notify: restart httpd

- name: Enable mpm prefork
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    regexp: '^#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
    line: 'LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
    backrefs: yes
  notify: restart httpd

- name: Disable mpm worker
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    regexp: '^LoadModule mpm_worker_module modules/mod_mpm_worker.so'
    line: '#LoadModule mpm_worker_module modules/mod_mpm_worker.so'
    backrefs: yes
  notify: restart httpd

- name: Disable mpm event
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    regexp: '^LoadModule mpm_event_module modules/mod_mpm_event.so'
    line: '#LoadModule mpm_event_module modules/mod_mpm_event.so'
    backrefs: yes
  notify: restart httpd
